language: node_js
node_js:
  - "6"
  - "7"
compiler:
  - gcc
  - clang
os:
  - linux
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
install:
  - cd truffle && npm install
script:
  - cd truffle && npm test
